# Generated by Django 5.0.1 on 2024-03-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wz_app', '0002_rename_numer_moje_wz_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moje_wz',
            name='slug',
            field=models.SlugField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
