# Generated by Django 5.0.1 on 2024-03-18 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wz_app', '0004_userwzownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='moje_wz',
            name='Data_dokumentu',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='moje_wz',
            name='Numer_samochodu',
            field=models.CharField(default='Transport własny', max_length=200),
        ),
        migrations.AddField(
            model_name='moje_wz',
            name='Odbiorca',
            field=models.CharField(default='', max_length=200),
        ),
    ]
