# Generated by Django 5.0.1 on 2024-03-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wz_app', '0005_moje_wz_data_dokumentu_moje_wz_numer_samochodu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moje_wz',
            name='Ilosc',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='moje_wz',
            name='Nazwa_produktu',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='moje_wz',
            name='Numer_produktu',
            field=models.CharField(default='', max_length=300),
        ),
    ]
